# Generated by Django 4.1.2 on 2022-10-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_emptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='empType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.emptype'),
        ),
    ]
