# Generated by Django 4.1.2 on 2022-10-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_empuser_emptype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='empType',
        ),
        migrations.DeleteModel(
            name='EmpType',
        ),
    ]
